/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_arielreyes;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Ariel
 */
public class Main extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form Main
     */
  
    public Main() {
        initComponents();
        
        
        
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_genero.getModel();
        model.addElement(new genero("Comedia"));
        model.addElement(new genero("Romance"));
        model.addElement(new genero("Terror"));
        model.addElement(new genero("SyFy"));
        model.addElement(new genero("Suspenso Accion"));
      cb_genero.setModel(model);
        cb_genero1.setModel(model);
        
        
        String st = "";
       // st += admi.getLista_claus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_programa = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jS_puntuacion = new javax.swing.JSpinner();
        jf_lanzamiento = new javax.swing.JFormattedTextField();
        jb_anime = new javax.swing.JRadioButton();
        jb_serie = new javax.swing.JRadioButton();
        jb_documentales = new javax.swing.JRadioButton();
        jb_peliculas = new javax.swing.JRadioButton();
        cb_genero = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tipo_boton = new javax.swing.ButtonGroup();
        ClaudiList = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jb_agregar_peli = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listas = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        menu_para_modpeliculas = new javax.swing.JPopupMenu();
        Mod = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        mod_lista = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jS_puntuacion1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jf_lanzamiento1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jb_anime1 = new javax.swing.JRadioButton();
        jb_serie1 = new javax.swing.JRadioButton();
        jb_documentales1 = new javax.swing.JRadioButton();
        jb_peliculas1 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cb_genero1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        List_cla = new javax.swing.JPopupMenu();
        Delete = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        listar = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Eliminare = new javax.swing.JDialog();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Modif = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        mood = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        cb_mod = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jMenuItem3 = new javax.swing.JMenuItem();
        abrir_archivo = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        JTree_parte = new javax.swing.JDialog();
        cb_Jtree = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel24 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        Eliminar_Modificar = new javax.swing.JPopupMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jLabel23 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("AGREGAR PROGRAMAS ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Puntuacion: ");

        jLabel4.setText("Año de lanzamiento:  ");

        jLabel5.setText("Tipo: ");

        jLabel6.setText("Genero: ");

        jS_puntuacion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        try {
            jf_lanzamiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tipo_boton.add(jb_anime);
        jb_anime.setText("Anime");

        tipo_boton.add(jb_serie);
        jb_serie.setText("Serie");

        tipo_boton.add(jb_documentales);
        jb_documentales.setText("Documental");

        tipo_boton.add(jb_peliculas);
        jb_peliculas.setText("Pelicula");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Agregar_programaLayout = new javax.swing.GroupLayout(Agregar_programa.getContentPane());
        Agregar_programa.getContentPane().setLayout(Agregar_programaLayout);
        Agregar_programaLayout.setHorizontalGroup(
            Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_programaLayout.createSequentialGroup()
                .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Agregar_programaLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Agregar_programaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Agregar_programaLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Agregar_programaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(jS_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Agregar_programaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jf_lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Agregar_programaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jb_anime)
                                .addGap(18, 18, 18)
                                .addComponent(jb_serie)
                                .addGap(18, 18, 18)
                                .addComponent(jb_documentales)
                                .addGap(18, 18, 18)
                                .addComponent(jb_peliculas))))
                    .addGroup(Agregar_programaLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(Agregar_programaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        Agregar_programaLayout.setVerticalGroup(
            Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_programaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jS_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jf_lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jb_anime)
                    .addComponent(jb_serie)
                    .addComponent(jb_documentales)
                    .addComponent(jb_peliculas))
                .addGap(18, 18, 18)
                .addGroup(Agregar_programaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Crear Su propia Claudilist");

        jLabel8.setText("Nombre de la lista: ");

        jLabel9.setText("Seleccione la pelicula a Agregar: ");

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Crear Lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar peli");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jl_listas.setModel(new DefaultListModel());
        jl_listas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_listas);

        jButton5.setText("Crear a Archivo de texto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClaudiListLayout = new javax.swing.GroupLayout(ClaudiList.getContentPane());
        ClaudiList.getContentPane().setLayout(ClaudiListLayout);
        ClaudiListLayout.setHorizontalGroup(
            ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClaudiListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(ClaudiListLayout.createSequentialGroup()
                .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClaudiListLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClaudiListLayout.createSequentialGroup()
                        .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClaudiListLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jb_agregar_peli, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ClaudiListLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClaudiListLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton3))
                            .addGroup(ClaudiListLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ClaudiListLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        ClaudiListLayout.setVerticalGroup(
            ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClaudiListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_agregar_peli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(ClaudiListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        Mod.setText("Modificar");
        Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModActionPerformed(evt);
            }
        });
        menu_para_modpeliculas.add(Mod);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        menu_para_modpeliculas.add(Eliminar);

        jLabel11.setText("Nombre: ");

        jLabel12.setText("Puntuacion: ");

        jS_puntuacion1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel13.setText("Año de lanzamiento:  ");

        try {
            jf_lanzamiento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Tipo: ");

        tipo_boton.add(jb_anime1);
        jb_anime1.setText("Anime");

        tipo_boton.add(jb_serie1);
        jb_serie1.setText("Serie");

        tipo_boton.add(jb_documentales1);
        jb_documentales1.setText("Documental");

        tipo_boton.add(jb_peliculas1);
        jb_peliculas1.setText("Pelicula");

        jLabel15.setText("Genero: ");

        jLabel16.setText("Modificar");

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mod_listaLayout = new javax.swing.GroupLayout(mod_lista.getContentPane());
        mod_lista.getContentPane().setLayout(mod_listaLayout);
        mod_listaLayout.setHorizontalGroup(
            mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mod_listaLayout.createSequentialGroup()
                .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel10))
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31)
                        .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jS_puntuacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jf_lanzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jb_anime1)
                        .addGap(18, 18, 18)
                        .addComponent(jb_serie1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_documentales1)
                        .addGap(18, 18, 18)
                        .addComponent(jb_peliculas1))
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel16))
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cb_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mod_listaLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        mod_listaLayout.setVerticalGroup(
            mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mod_listaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jS_puntuacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jf_lanzamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jb_anime1)
                    .addComponent(jb_serie1)
                    .addComponent(jb_documentales1)
                    .addComponent(jb_peliculas1))
                .addGap(30, 30, 30)
                .addGroup(mod_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cb_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        Delete.setText("Eliminar");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        List_cla.add(Delete);

        jMenuItem4.setText("jMenuItem4");

        jButton6.setText("VER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel17.setText("Listar");

        jButton7.setText("Limpiar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listarLayout = new javax.swing.GroupLayout(listar.getContentPane());
        listar.getContentPane().setLayout(listarLayout);
        listarLayout.setHorizontalGroup(
            listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarLayout.createSequentialGroup()
                .addGroup(listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(listarLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel17))
                    .addGroup(listarLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton6)
                        .addGap(63, 63, 63)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        listarLayout.setVerticalGroup(
            listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(64, 64, 64))
        );

        jButton8.setText("Mostrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Eliminar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jLabel18.setText("Indice a eliminar");

        javax.swing.GroupLayout EliminareLayout = new javax.swing.GroupLayout(Eliminare.getContentPane());
        Eliminare.getContentPane().setLayout(EliminareLayout);
        EliminareLayout.setHorizontalGroup(
            EliminareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminareLayout.createSequentialGroup()
                .addGroup(EliminareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminareLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(EliminareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EliminareLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EliminareLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel18)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        EliminareLayout.setVerticalGroup(
            EliminareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addGroup(EliminareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jLabel19.setText("Indice a modificar");

        jButton11.setText("Modificar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton10.setText("Mostrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifLayout = new javax.swing.GroupLayout(Modif.getContentPane());
        Modif.getContentPane().setLayout(ModifLayout);
        ModifLayout.setHorizontalGroup(
            ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifLayout.createSequentialGroup()
                .addGroup(ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModifLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel19))
                    .addGroup(ModifLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModifLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton11))
                    .addGroup(ModifLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton10)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        ModifLayout.setVerticalGroup(
            ModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel20.setText("Nombre: ");

        jLabel21.setText("Seleccion: ");

        jList2.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jList2);

        jButton12.setText("Agregar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Limpiar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Agregar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moodLayout = new javax.swing.GroupLayout(mood.getContentPane());
        mood.getContentPane().setLayout(moodLayout);
        moodLayout.setHorizontalGroup(
            moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moodLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(cb_mod, 0, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moodLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moodLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moodLayout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13)
                        .addGap(104, 104, 104))))
        );
        moodLayout.setVerticalGroup(
            moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moodLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(moodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)))
        );

        jMenuItem3.setText("jMenuItem3");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane7.setViewportView(jTextArea4);

        jLabel22.setText("Buscar Archivo: ");

        jButton15.setText("Buscar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abrir_archivoLayout = new javax.swing.GroupLayout(abrir_archivo.getContentPane());
        abrir_archivo.getContentPane().setLayout(abrir_archivoLayout);
        abrir_archivoLayout.setHorizontalGroup(
            abrir_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrir_archivoLayout.createSequentialGroup()
                .addGroup(abrir_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abrir_archivoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abrir_archivoLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        abrir_archivoLayout.setVerticalGroup(
            abrir_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrir_archivoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(abrir_archivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jButton15))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Claudilist");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree1MousePressed(evt);
            }
        });
        jScrollPane9.setViewportView(jTree1);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("IMPLEMENTACION DEL JTREE");

        jButton17.setText("Añadir");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Limpiar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JTree_parteLayout = new javax.swing.GroupLayout(JTree_parte.getContentPane());
        JTree_parte.getContentPane().setLayout(JTree_parteLayout);
        JTree_parteLayout.setHorizontalGroup(
            JTree_parteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTree_parteLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(cb_Jtree, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JTree_parteLayout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addGroup(JTree_parteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addComponent(jButton18)
                .addGap(120, 120, 120))
        );
        JTree_parteLayout.setVerticalGroup(
            JTree_parteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTree_parteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JTree_parteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Jtree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JTree_parteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JTree_parteLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JTree_parteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton18)
                        .addGap(24, 24, 24))))
        );

        jMenuItem11.setText("Eliminar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Eliminar_Modificar.add(jMenuItem11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel23.setText("Agregar Una nueva Direccion ");

        jButton16.setText("Direccion");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Intrucciones: Si desea ejercutar una lista ya creada \nusted debe se seleccionar la direccion de esa lista \n\n- Si usted quiere meter informacion a un archivo TXT \ndebera crearlo y luego pasar la direccion de el para poder\ntrabajar sobre el doc");
        jTextArea5.setEnabled(false);
        jScrollPane8.setViewportView(jTextArea5);

        jMenu2.setText("Opciones");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Agregar a programa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Crear ClaudiList");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.setText("CRUD Archivos de texto");

        jMenuItem5.setText("Listar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Eliminar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Modificar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenu2.add(jMenu1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Abrir un Archivo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Crear txt");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("JTree");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel23)
                        .addGap(45, 45, 45)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        agregar_lista();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {

            String nombre = jt_nombre.getText();
            int puntuacion = (int) jS_puntuacion.getValue();
            int year_lanzamiento = Integer.parseInt(jf_lanzamiento.getText());
            String tipo = "";
            if(jb_anime.isSelected()){
                tipo = "Anime";
            } 
            if(jb_serie.isSelected()){
                tipo = "Serie";
            } 
            if (jb_documentales.isSelected()) {
                tipo = "Documental";
            }
            if (jb_peliculas.isSelected()) {
                tipo = "Pelicula";
            }
            
            String genero = cb_genero.getSelectedItem().toString();
            
            programas pro = new programas(nombre, puntuacion, year_lanzamiento, tipo, genero);
            DefaultComboBoxModel pelis = (DefaultComboBoxModel) jb_agregar_peli.getModel();            
            pelis.addElement(pro);
         
            
            jb_agregar_peli.setModel(pelis);
            cb_mod.setModel(pelis);
            cb_Jtree.setModel(pelis);
            JOptionPane.showMessageDialog(this, "Agregado Correctamente");
            jS_puntuacion.setValue(0);
            jt_nombre.setText("");
            jf_lanzamiento.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        agregar_claudia();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model_combo = (DefaultComboBoxModel) jb_agregar_peli.getModel();
        DefaultListModel model_lista = (DefaultListModel) jList1.getModel();
        programas persona = (programas) jb_agregar_peli.getSelectedItem();
        model_lista.addElement(persona);
        jList1.setModel(model_lista);
       
        jb_agregar_peli.setModel(model_combo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            String nombre = jTextField1.getText();
            ListModel d = jList1.getModel();
            ArrayList<programas> paso = new ArrayList();
            for (int i = 0; i < d.getSize(); i++) {
                paso.add((programas) d.getElementAt(i));
            }

            claudilist clau = new claudilist(nombre);
            clau.setProgra(paso);
            DefaultListModel mod_lis = (DefaultListModel) jl_listas.getModel();
            mod_lis.addElement(clau);
            jl_listas.setModel(mod_lis);

            JOptionPane.showMessageDialog(this, "Agregado correctamente");

            lista_claudia.add(clau);
            DefaultListModel dd = (DefaultListModel) jList1.getModel();
            dd.removeAllElements();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown()){
        if(jList1.getSelectedIndex() >=0){
            menu_para_modpeliculas.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        
         
        
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModActionPerformed
        // TODO add your handling code here:
        mod_pelis();
    }//GEN-LAST:event_ModActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try{
           if(jList1.getSelectedIndex() >=0){
               
               String nombre = jTextField2.getText(); 
               String tipo = "";
         int puntuacion = (int) jS_puntuacion1.getValue(); 
         int year = Integer.parseInt(jf_lanzamiento1.getText());
            if(jb_anime1.isSelected()){
                tipo = "Anime";
                }                
                if (jb_serie1.isSelected()) {
                    tipo = "Serie";
                }                
                if (jb_documentales1.isSelected()) {
                    tipo = "Documental";
                }
                if (jb_peliculas1.isSelected()) {
                    tipo = "Pelicula";
                }
                String genero = cb_genero1.getSelectedItem().toString();                
                DefaultListModel model = (DefaultListModel) jList1.getModel();
                ((programas) model.get(jList1.getSelectedIndex())).setNombre(nombre);
                ((programas) model.get(jList1.getSelectedIndex())).setGenero(genero);
                ((programas) model.get(jList1.getSelectedIndex())).setTipo(tipo);
                ((programas) model.get(jList1.getSelectedIndex())).setPuntuacion(puntuacion);
                ((programas) model.get(jList1.getSelectedIndex())).setTipo(tipo);
                ((programas) model.get(jList1.getSelectedIndex())).setYear_lanzamiento(year);
                jList1.setModel(model);
            }
            

            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR");
        
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
        if(jList1.getSelectedIndex()>=0){
        DefaultListModel model = (DefaultListModel)jList1.getModel(); 
        model.remove(jList1.getSelectedIndex());
            jList1.setModel(model);
        }


    }//GEN-LAST:event_EliminarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        admi_claudia_lista admi = new admi_claudia_lista(jTextField6.getText());
        admi.cargarArchivo();
        //  ListModel = jl_listas.getModel(); 
        ListModel d = jl_listas.getModel();
        for (int i = 0; i < d.getSize(); i++) {
            admi.getLista_claus().add((claudilist) d.getElementAt(i));
        }
        
        
       
        JOptionPane.showMessageDialog(this, "Correcto");
        try {
             admi.escribeArchivo();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
 

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jl_listasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listasMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown()){
         if(jl_listas.getSelectedIndex() >=0 ){
             List_cla.show(evt.getComponent(), evt.getX(), evt.getY());
         }   
        }
    }//GEN-LAST:event_jl_listasMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        
if(jl_listas.getSelectedIndex() >=0 ){
             DefaultListModel model = (DefaultListModel) jl_listas.getModel(); 
             model.remove(jl_listas.getSelectedIndex());
         }           
    }//GEN-LAST:event_DeleteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        lis_archivo();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        admi_claudia_lista admi = new admi_claudia_lista(jTextField6.getText());
        admi.cargarArchivo();
        String st = "";
        st += admi.getLista_claus();
        // System.out.println(admi.getLista_claus() + "=====>" + c);

        jTextArea1.setText(st);




    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        lis_ar_eli();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         admi_claudia_lista admi = new admi_claudia_lista(jTextField6.getText());
        admi.cargarArchivo();
        String st = "";
        //st += admi.getLista_claus();
        // System.out.println(admi.getLista_claus() + "=====>" + c);
String ac = "";
        for (int i = 0; i < admi.getLista_claus().size(); i++) {
            ac += admi.getLista_claus().get(i) + "\n" + "\n";

        }
        String aci = "";
        int cont = 0;
        int cont2 = 0;
        for (claudilist c : admi.getLista_claus()) {
            aci += ")" + c.getNombre() + "\n";
            cont++;

        }

        jTextArea2.setText(aci);


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        admi_claudia_lista admi = new admi_claudia_lista(jTextField6.getText());
        int indice = Integer.parseInt(jTextField3.getText());
        admi.cargarArchivo();
        admi.getLista_claus().remove(indice);
        JOptionPane.showMessageDialog(this, "Eliminado");
        jTextArea2.setText("");
        try {
            admi.escribeArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        modif();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        moode();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
           admi_claudia_lista admi = new admi_claudia_lista(jTextField6.getText());
        admi.cargarArchivo();
        String st = "";
        //st += admi.getLista_claus();
        // System.out.println(admi.getLista_claus() + "=====>" + c);
String ac = "";
        for (int i = 0; i < admi.getLista_claus().size(); i++) {
            ac += admi.getLista_claus().get(i) + "\n" + "\n";

        }
        String aci = "";
        int cont = 0;
        int cont2 = 0;
        for (claudilist c : admi.getLista_claus()) {
            aci += ")" + c.getNombre() + "\n";
            cont++;

        }

        jTextArea3.setText(aci);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         DefaultComboBoxModel model_combo = (DefaultComboBoxModel) cb_mod.getModel();
        DefaultListModel model_lista = (DefaultListModel) jList2.getModel();
        programas persona = (programas) cb_mod.getSelectedItem();
        model_lista.addElement(persona);
        jList2.setModel(model_lista);
       
        cb_mod.setModel(model_combo);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        if (jTextField4 == null) {
            JOptionPane.showMessageDialog(this, "ERROR");
        } else {

            try {
                
                int indice = Integer.parseInt(jTextField4.getText());
                ListModel d = jList2.getModel();
                ArrayList<programas> t = new ArrayList();
                for (int i = 0; i < d.getSize(); i++) {
                    t.add((programas) d.getElementAt(i));
                }
                String nombre = jTextField5.getText();                
                claudilist clau = new claudilist(nombre);                
                clau.setProgra(t);
                admi_claudia_lista admi = new admi_claudia_lista(jTextField6.getText());
                admi.cargarArchivo();
                admi.getLista_claus().set(indice, clau);
                admi.escribeArchivo();
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ERROR");
            }
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jList2.removeAll();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        jTextArea4.setText("");
        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
            FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes", "jpg", "pgn", "bmp");
            jfc.setFileFilter(filtro);
            jfc.addChoosableFileFilter(filtro2);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea = "";
                jTextArea4.setText("");
                while ((linea = br.readLine()) != null) {
                    jTextArea4.append(linea);
                    jTextArea4.append("\n");
                }
            }
        } catch (Exception e) {

        }



    }//GEN-LAST:event_jButton15ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        abrir();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showOpenDialog(this);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File fichero = null;

                if (jfc.getFileFilter().getDescription().equals("Archivo de texto")) {
                    fichero = new File(jfc.getSelectedFile().getPath() + ".txt");

                } else {
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);

                bw.flush();
                JOptionPane.showMessageDialog(this, "TEXTO AGREGADO");
            } catch(Exception e){

            }
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        JFileChooser filecho = new JFileChooser();
       
        int seleccion = filecho.showOpenDialog(this);
        
            File dir = filecho.getSelectedFile();
        
       
        jTextField6.setText( dir.getAbsolutePath());
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        frame_tree();
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here
         DefaultTreeModel tree_model = (DefaultTreeModel) jTree1.getModel(); 
            DefaultMutableTreeNode model_raiz = (DefaultMutableTreeNode) tree_model.getRoot();
        //DefaultMutableTreeNode persona_nodo;
       // DefaultListModel lista_model = (DefaultListModel) jl_estudiantes.getModel();
        programas g = (programas) cb_Jtree.getSelectedItem();
      


           // nombre = ((estudiantes)lista_model.get(jl_estudiantes.getSelectedIndex())).getNombre();
            
            int centinela = -1; 
            for (int i = 0; i < model_raiz.getChildCount(); i++) {
                if(model_raiz.getChildAt(i).toString().equals( g.getNombre())){
                DefaultMutableTreeNode P = new DefaultMutableTreeNode(new programas(g.getNombre(), g.getPuntuacion(), g.getYear_lanzamiento(), g.getTipo(), g.getGenero()));
                ((DefaultMutableTreeNode) model_raiz.getChildAt(i)).add(P);
                centinela = 1;
            }
        }
        if (centinela == -1) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(g.getNombre());
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new programas(g.getNombre(), g.getPuntuacion(), g.getYear_lanzamiento(), g.getTipo(), g.getGenero()));
            n.add(p);
            model_raiz.add(n);
        }
        tree_model.reload();

        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jTree1.removeAll();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTree1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MousePressed
        // TODO add your handling code here:
 if(evt.isMetaDown()){
       
           if (evt.isMetaDown()) {
               // aca capturamos la fila mas cercana a donde se hace click 
               int row = jTree1.getClosestRowForLocation(evt.getX(), evt.getY());
               // aca la dejamos como fila seleccionada
                jTree1.setSelectionRow(row);
                // sacamos el objeto 
                Object obj = jTree1.getSelectionPath().getLastPathComponent();
                // agarramos el nodo seleccionado que es el objeto 
                nodo_seleccionado = (DefaultMutableTreeNode) obj;
                // se valida que hayan clientes en el nodo 
                if (nodo_seleccionado.getUserObject() instanceof programas) {
                    programa_seleccionado = (programas) nodo_seleccionado.getUserObject(); // se pasa a la variable que es persona 
                    Eliminar_Modificar.show(evt.getComponent(), evt.getX(), evt.getY()); // se muestra el menu 
                }

            }

        }
    }//GEN-LAST:event_jTree1MousePressed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(this, "Seguro de eliminar? ", "Confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE); // se manda el mensaje 
        if (delete == JOptionPane.OK_OPTION) { // se confirma la opcion 
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();  // se captura el modelo 
            model.removeNodeFromParent(nodo_seleccionado); // se remueve el modelo 
            model.reload(); // se manda la imagen 
        }

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
                 
       
           if (evt.isMetaDown()) {
               // aca capturamos la fila mas cercana a donde se hace click 
               int row = jTree1.getClosestRowForLocation(evt.getX(), evt.getY());
               // aca la dejamos como fila seleccionada
               jTree1.setSelectionRow(row);
               // sacamos el objeto 
               Object obj = jTree1.getSelectionPath().getLastPathComponent();
                // agarramos el nodo seleccionado que es el objeto 
                nodo_seleccionado = (DefaultMutableTreeNode) obj;
                // se valida que hayan clientes en el nodo 
                if (nodo_seleccionado.getUserObject() instanceof programas) {
                    programa_seleccionado = (programas) nodo_seleccionado.getUserObject(); // se pasa a la variable que es persona 
                    Eliminar_Modificar.show(evt.getComponent(), evt.getX(), evt.getY()); // se muestra el menu 
                }

            }

        
    }//GEN-LAST:event_jTree1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

     public void agregar_lista() {
        Agregar_programa.dispose();
        Agregar_programa.pack();
        Agregar_programa.setModal(true);
        Agregar_programa.setLocationRelativeTo(this);
        Agregar_programa.setVisible(true);
    }
     
     public void agregar_claudia() {
        ClaudiList.dispose();
        ClaudiList.pack();
        ClaudiList.setModal(true);
        ClaudiList.setLocationRelativeTo(this);
        ClaudiList.setVisible(true);
    }
     
        public void mod_pelis() {
        mod_lista.dispose();
        mod_lista.pack();
        mod_lista.setModal(true);
        mod_lista.setLocationRelativeTo(this);
        mod_lista.setVisible(true);
    }
          public void lis_archivo() {
        listar.dispose();
        listar.pack();
        listar.setModal(true);
        listar.setLocationRelativeTo(this);
        listar.setVisible(true);
    }

    public void lis_ar_eli() {
        Eliminare.dispose();
        Eliminare.pack();
        Eliminare.setModal(true);
        Eliminare.setLocationRelativeTo(this);
        Eliminare.setVisible(true);
    }
    
    
    public void modif() {
        Modif.dispose();
        Modif.pack();
        Modif.setModal(true);
        Modif.setLocationRelativeTo(this);
        Modif.setVisible(true);
    }
    
     public void moode() {
        mood.dispose();
        mood.pack();
        mood.setModal(true);
        mood.setLocationRelativeTo(this);
        mood.setVisible(true);
    }
      public void abrir() {
        abrir_archivo.dispose();
        abrir_archivo.pack();
        abrir_archivo.setModal(true);
        abrir_archivo.setLocationRelativeTo(this);
        abrir_archivo.setVisible(true);
    }
        public void frame_tree() {
        //abrir_archivo.dispose();
        JTree_parte.pack();
        JTree_parte.setModal(true);
        JTree_parte.setLocationRelativeTo(this);
        JTree_parte.setVisible(true);
    }
    
 DefaultMutableTreeNode nodo_seleccionado; 
    programas programa_seleccionado; 
    
    private ArrayList<claudilist> lista_claudia = new ArrayList(); 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar_programa;
    private javax.swing.JDialog ClaudiList;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JPopupMenu Eliminar_Modificar;
    private javax.swing.JDialog Eliminare;
    private javax.swing.JDialog JTree_parte;
    private javax.swing.JPopupMenu List_cla;
    private javax.swing.JMenuItem Mod;
    private javax.swing.JDialog Modif;
    private javax.swing.JDialog abrir_archivo;
    private javax.swing.JComboBox<String> cb_Jtree;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_genero1;
    private javax.swing.JComboBox<String> cb_mod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSpinner jS_puntuacion;
    private javax.swing.JSpinner jS_puntuacion1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> jb_agregar_peli;
    private javax.swing.JRadioButton jb_anime;
    private javax.swing.JRadioButton jb_anime1;
    private javax.swing.JRadioButton jb_documentales;
    private javax.swing.JRadioButton jb_documentales1;
    private javax.swing.JRadioButton jb_peliculas;
    private javax.swing.JRadioButton jb_peliculas1;
    private javax.swing.JRadioButton jb_serie;
    private javax.swing.JRadioButton jb_serie1;
    private javax.swing.JFormattedTextField jf_lanzamiento;
    private javax.swing.JFormattedTextField jf_lanzamiento1;
    private javax.swing.JList<String> jl_listas;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JDialog listar;
    private javax.swing.JPopupMenu menu_para_modpeliculas;
    private javax.swing.JDialog mod_lista;
    private javax.swing.JDialog mood;
    private javax.swing.ButtonGroup tipo_boton;
    // End of variables declaration//GEN-END:variables
}
